//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4438
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LR2_ISRPOEntities : DbContext
    {
        private static LR2_ISRPOEntities _context;
        public LR2_ISRPOEntities()
            : base("name=LR2_ISRPOEntities")
        {
        }
        public static LR2_ISRPOEntities GetContext()
        {
            if (_context == null)
                _context = new LR2_ISRPOEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Orders> Orders { get; set; }
    }
}
