//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4438
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServicesTableEntities : DbContext
    {
        public ServicesTableEntities()
            : base("name=ServicesTableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<SecondServices> SecondServices { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
