//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4438
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public string Код_заказа { get; set; }
        public string Дата_создания { get; set; }
        public string Время_заказа { get; set; }
        public string Код_клиента { get; set; }
        public string Услуги { get; set; }
        public string Статус { get; set; }
        public string Дата_закрытия { get; set; }
        public string Время_проката { get; set; }
    }
}
