//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4438
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public string ordercode { get; set; }
        public string createdate { get; set; }
        public string ordertime { get; set; }
        public string clientcode { get; set; }
        public string feauters { get; set; }
        public string status { get; set; }
        public string enddate { get; set; }
        public string rentaltime { get; set; }
    }
}
