//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4438
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public string OrderCode { get; set; }
        public string OrderTime { get; set; }
        public string CreateDate { get; set; }
        public int ClientCode { get; set; }
        public string Services { get; set; }
        public string Status { get; set; }
        public string CloseData { get; set; }
        public string RentialTime { get; set; }
    }
}
