//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4438
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public string OrderCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.TimeSpan> OrderTime { get; set; }
        public Nullable<int> ClientCode { get; set; }
        public string Services { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string RentalTime { get; set; }
 
    }
}
