//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4438
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecondServices
    {
        public int Id { get; set; }
        public string OrderCode { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string OrderTime { get; set; }
        public int UserCode { get; set; }
        public string NumberServices { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string RentalTime { get; set; }
    }
}
