//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4438
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int ID { get; set; }
        public string Service_Name { get; set; }
        public string Service_Type { get; set; }
        public string Service_Code { get; set; }
        public Nullable<int> Cost { get; set; }
    }
}
