//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4438.Safiullin_4438.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelEntity
    {
        public int Id { get; set; }
        public string ServiceName { get; set; }
        public string ServiceType { get; set; }
        public string ServiceCode { get; set; }
        public int ServicePrice { get; set; }
    }
}
